apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    openshift.io/host.generated: "true"
  labels:
    app: foca-webhook
    kingdom: '{{ .Values.kingdom }}'
  name: foca-webhook
spec:
  host: foca-webhook-{{ .Values.kingdom }}.apps-crc.testing
  port:
    targetPort: 8080-tcp
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: foca-webhook
    weight: 100
  wildcardPolicy: None
