# Default values for foca-webhook-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: sre-tooling
replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""
service:
  type: ClusterIP
  port: 80
